# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170423_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
